### ISSUE TITLE
Postulación de charla - Juan Sebastian Mendoza

### ISSUE THREAD

**Issue by JuanSebastianM** [barranquillajs/Meetups#1]
> Nuestros eventos se rigen por el siguiente [Código de conducta](https://github.com/barranquillajs/codigo-de-conducta) - [https://github.com/barranquillajs/codigo-de-conducta](https://github.com/barranquillajs/codigo-de-conducta)

> Antes de suscribir una charla, recuerda revísarlo para ver si estamos en la misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [x] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Juan Sebastian Mendoza Pérez

## ¿Cuál es el título de tu charla?
¿Cómo es eso de ser un desarrollador autodidacta y no fallar en el intento?

## Danos una descripción de tu charla (20 palabras)
Hablaré sobre lo que es ser autodidacta de forma general, autodidacta y universidad (sin intención de polémica), y consejos para evitar fallar durante el proceso de aprendizaje.

## ¿Tienes alguna red social donde podamos contactarte?
[Twitter](https://twitter.com/JuanMendozaDev), [GitHub](https://github.com/JuanSebastianM).

## ¿Representas a alguna compañía o empresa?
Devsu LLC.

## ¿Qué tipo de conector tiene tu notebook?

- [x] HDMI
- [ ] Mini DisplayPort
- [ ] VGA

## ¿Quieres agregar algo más?
No.

-----------
> Muchas Gracias!
> El equipo de @barranquillajs/meetup

**Comment by lporras** [comment]
Excelente, gracias Juan por postular. ¿Te parece bien dar la charla este 23 de Agosto?

**Comment by JuanSebastianM** [comment]
> Excelente, gracias Juan por postular. ¿Te parece bien dar la charla este 23 de Agosto?

Claro que sí!

**Comment by lporras** [comment]
Listo entonces confirmado para este 23 de Agosto, apenas tenga el venue confirmado voy a publicar el evento en meetup.com

**Comment by lporras** [comment]
Charla presentada el 23 de Agosto.
