### ISSUE TITLE
Postulación de charla - Jesus Hernandez

### ISSUE THREAD

**Issue by JesuHrz** [barranquillajs/Meetups#11]
## ¿Qué tipo de presentación quieres hacer?

- [x] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?

Jesus Hernandez

## ¿Cuál es el título de tu charla?
Desmitificando Jest

## Danos una descripción de tu charla (20 palabras)
En esta charla vamos a desmitificar y crear nuestro propio Jest desde 0.

## ¿Tienes alguna red social donde podamos contactarte?
Instagram - Twitter - Github: Jesuhrz

## ¿Qué tipo de conector tiene tu notebook?

- [x] HDMI
- [ ] Mini DisplayPort
- [ ] VGA

-----------
> Muchas Gracias!
> El equipo de @barranquillajs/meetup

**Comment by lporras** [comment]
Buena bro, lo agendaremos para nuestro meetup de 16 Marzo 2023
