### ISSUE TITLE
Javascript as power 💪🏽

### ISSUE THREAD

**Issue by edgeorgie** [barranquillajs/Meetups#13]
> Nuestros eventos se rigen por el siguiente [Código de conducta](https://github.com/barranquillajs/codigo-de-conducta) - [https://github.com/barranquillajs/codigo-de-conducta](https://github.com/barranquillajs/codigo-de-conducta)

> Antes de suscribir una charla, recuerda revísarlo para ver si estamos en la misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [X] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Edwin Jorge

## ¿Cuál es el título de tu charla?

Javascript as power💪🏽

## Danos una descripción de tu charla (20 palabras)

Inicios de Javascript y su estado actual. ¿Cómo funciona javascript en el navegador?

## Danos una breve bio acerca de tí (20 palabras o menos)

Soy Edwin Jorge (mi apellido es Jorge), trabajo como Software Engineer en Mercado Libre. Actualmente estoy en noveno semestre de ingeniería electrónica.

## ¿Tienes alguna red social donde podamos contactarte?

https://twitter.com/edgeorgie_

## ¿Representas a alguna compañía o empresa?
No.
## ¿Qué tipo de conector tiene tu notebook?

- [X] HDMI
- [ ] Mini DisplayPort
- [ ] VGA

## ¿Quieres agregar algo más?

-----------
> Muchas Gracias!
> El equipo de @barranquillajs/meetup

**Comment by lporras** [comment]
Excelente, gracias @edgeorgie por tu interés en participar, vamos a coordinar para ver si es posible para abril o mayo, te estaremos contactando.
