### ISSUE TITLE
Backend: Más allá de las APIs

### ISSUE THREAD

**Issue by gabo-cs** [barranquillajs/Meetups#14]
## ¿Qué tipo de presentación quieres hacer?

- [x] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Gabriel Coronado

## ¿Cuál es el título de tu charla?
Backend: Más allá de las APIs

## Danos una descripción de tu charla (20 palabras)

Indagaremos en todos aquellos aspectos del Backend que van más allá de solamente APIs y endpoints.

## Danos una breve bio acerca de ti (20 palabras o menos)

 Me llamo Gabriel Coronado, me pueden decir Gabo, soy Software Engineer en una startup FinTech de Silicon Valley y mis hobbies son el ajedrez y el fútbol. 

## ¿Tienes alguna red social donde podamos contactarte?

Website: https://gabo-cs.github.io/

## ¿Representas a alguna compañía o empresa?
No.
## ¿Qué tipo de conector tiene tu notebook?

- [x] HDMI
- [ ] Mini DisplayPort
- [ ] VGA

## ¿Quieres agregar algo más?
A lo largo de mis años de experiencia como backend, me he enfrentado a muchas concepciones erróneas que se tiene sobre el backend, ya que usualmente se cree que éste consiste únicamente de crear endpoints para APIs. Muchos se preguntan: ¿en qué trabaja un backend cuando no está trabajando en el API ? Esta charla responderá esa pregunta y muchas más!

-----------
> Muchas Gracias!
> El equipo de @barranquillajs/meetup

**Comment by makinox** [comment]
Vamos a cerrar tu issue @gabo-cs  porque ya cuadramos esta charla en el evento de caribeded.org.
Avísanos para volver a abrir el issue o dudas extras, gracias.
