### ISSUE TITLE
La Danza de los Tests en el Mundo del Software

### ISSUE THREAD

**Issue by djom202** [barranquillajs/Meetups#16]
> Nuestros eventos se rigen por el siguiente [Código de conducta](https://github.com/barranquillajs/codigo-de-conducta) - [https://github.com/barranquillajs/codigo-de-conducta](https://github.com/barranquillajs/codigo-de-conducta)

> Antes de suscribir una charla, recuerda revísarlo para ver si estamos en la misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [x] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Jonathan Olier Miranda

## ¿Cuál es el título de tu charla?

La Danza de los Tests en el Mundo del Software

## Danos una descripción de tu charla (20 palabras)

Exploraremos las pruebas E2E, frameworks, mantenimiento, escalabilidad, y desafíos, con ejemplos y consejos prácticos.

## Danos una breve bio acerca de tí (20 palabras o menos)

Soy Ingeniero de Software con +11 años de experiencia, trabajo como QA Engineer Specialist en Simetrick y me apasiona el codigo en todo su explendor.

## ¿Tienes alguna red social donde podamos contactarte?

Github: https://github.com/djom202
Linkedin: https://www.linkedin.com/in/djom202

## ¿Representas a alguna compañía o empresa?
No

## ¿Qué tipo de conector tiene tu notebook?

- [ ] HDMI
- [ ] Mini DisplayPort
- [ ] VGA
- [x] USB-C

## ¿Quieres agregar algo más?

Mi Personal page: https://djom202.github.io/

-----------
> Muchas Gracias!
> El equipo de @barranquillajs/meetup

**Comment by lporras** [comment]
@djom202 Tienes disponibilidad para dar tu charla en el próximo meetup el día 17 de Agosto 2023?
