### ISSUE TITLE
Postulación de charla - Gabriel Coronado

### ISSUE THREAD

**Issue by gabo-cs** [barranquillajs/Meetups#2]
> Nuestros eventos se rigen por el siguiente [Código de conducta](https://github.com/barranquillajs/codigo-de-conducta) - [https://github.com/barranquillajs/codigo-de-conducta](https://github.com/barranquillajs/codigo-de-conducta)

> Antes de suscribir una charla, recuerda revísarlo para ver si estamos en la misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [x] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Gabriel Coronado

## ¿Cuál es el título de tu charla?
Adquiere un inglés verdaderamente avanzado de manera 100% autodidacta.  

## Danos una descripción de tu charla (20 palabras)
Hablaré y compartiré los recursos que utilicé personalmente para alcanzar un nivel C1/C2 en el idioma y cómo me ayudó a hoy tener un trabajo en una startup de Silicon Valley. Esto, con el fin de demostrar que cualquiera puede conseguirlo y con el fin ayudar a la comunidad en esta travesía!

## ¿Tienes alguna red social donde podamos contactarte?
Website: https://gabo-cs.github.io/

## ¿Qué tipo de conector tiene tu notebook?

- [x] HDMI
- [ ] Mini DisplayPort
- [ ] VGA

## ¿Quieres agregar algo más?
Aunque esta charla no estaría directamente relacionado con el mundo JS, sí que tiene un gran impacto en el mundo del desarrollo de software y puede beneficiar a cualquier desarrollador interesado en mejorar sus skills en el idioma universal!
Una combinación de disciplina y esfuerzo es lo necesario para llegar a ese nivel soñado de inglés avanzado de forma 100% autodidacta y gratis.

-----------
> Muchas Gracias!
> El equipo de @barranquillajs/meetup

**Comment by lporras** [comment]
@gabo-cs que te parece dar la charla para el meetup de octubre?

**Comment by lporras** [comment]
@gabo-cs nos podrías pasar una bio acerca de ti pasa usarla en la descripción del evento?

**Comment by gabo-cs** [comment]
> @gabo-cs nos podrías pasar una bio acerca de ti pasa usarla en la descripción del evento?

Hola, soy Gabriel Coronado, tengo 23 años, soy amante de la computación y actualmente me desempeño como Software Engineer en una startup estadounidense, cuento con 5 años de experiencia profesional pero me enamoré de la programación hace 8 y desde entonces nació mi yo autodidacta. Me encantan los lenguajes (tanto de humanos como de máquina)

**Comment by lporras** [comment]
Esta charla se hará en el meetup del 11 de octubre.
