### ISSUE TITLE
SST - Infraestructura como código, pero con JavaScript

### ISSUE THREAD

**Issue by JohnnyScript** [barranquillajs/Meetups#21]
> Nuestros eventos se rigen por el siguiente [Código de conducta](https://github.com/barranquillajs/codigo-de-conducta) - [https://github.com/barranquillajs/codigo-de-conducta](https://github.com/barranquillajs/codigo-de-conducta)

## ¿Qué tipo de presentación quieres hacer?

- [x] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
* Johnny Pacheco

## ¿Cuál es el título de tu charla?

* SST - Infraestructura como código, pero con JavaScript

## Danos una descripción de tu charla (20 palabras)

* SST: La potente herramienta que unifica tu aplicación y su infraestructura AWS en un solo sitio. Exploraremos su funcionalidad con ejemplos prácticos y reales en esta charla.

## Danos una breve bio acerca de tí (20 palabras o menos)

* Johnny Pacheco, Desarrollador FullStack con experiencia en múltiples Startups. Especializado en crear apps escalables y amante de la cocina gourmet y la música.

## ¿Tienes alguna red social donde podamos contactarte?
 -  [Linkedin](https://www.linkedin.com/in/nypakun/)
 -  [Instagram](https://www.instagram.com/j0hnnydev/)

## ¿Representas a alguna compañía o empresa?
 * No

## ¿Qué tipo de conector tiene tu notebook?

- [X] HDMI
- [ ] Mini DisplayPort
- [ ] VGA

-----------
> Muchas Gracias!
> El equipo de @barranquillajs/meetup

**Comment by lporras** [comment]
Hola @JohnnyScript  tienes disponibilidad para dar esta charla en el meetup de febrero 2024?
Tenemos pensado hacerlo el 22 de febrero.  Aceptame en Linkedin (https://www.linkedin.com/in/lporras/) para que coordinemos

**Comment by JohnnyScript** [comment]
Confirmo disponibilidad para ese dia y ya estamos en contacto en Linkedin!
