### ISSUE TITLE
Como poner un div en React Native: React Strict DOM

### ISSUE THREAD

**Issue by scidroid** [barranquillajs/Meetups#24]
> Nuestros eventos se rigen por el siguiente [Código de conducta](https://github.com/barranquillajs/codigo-de-conducta) - [https://github.com/barranquillajs/codigo-de-conducta](https://github.com/barranquillajs/codigo-de-conducta)

> Antes de suscribir una charla, recuerda revísarlo para ver si estamos en la misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [x] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Juan Almanza

## ¿Cuál es el título de tu charla?
Como poner un div en React Native: React Strict DOM

## Danos una descripción de tu charla (20 palabras)
Ver la nueva api experimental de react que permitiría hacer componentes y estilos que funcionen tanto en react-dom como en react-native (esencialmente usar un div en react native).

## Danos una breve bio acerca de tí (20 palabras o menos)
Soy Juan, soy founder y hago producto en Pulpoo, investigación en applied machine learning y pro player de call of duty.

## ¿Tienes alguna red social donde podamos contactarte?
instagram.com/scidroid
juan@pulpoo.com

## ¿Representas a alguna compañía o empresa?
No

## ¿Qué tipo de conector tiene tu notebook?

- [x] HDMI
- [ ] Mini DisplayPort
- [ ] VGA

## ¿Quieres agregar algo más?

-----------
> Muchas Gracias!
> El equipo de @barranquillajs/meetup

**Comment by lporras** [comment]
Hola Juan @scidroid ,
Tienes disponibildiad para dar esta charla en nuestro meetup el día 21 de Marzo?
