### ISSUE TITLE
Mapas 3D en JS y modelos de Gemini en Google Places

### ISSUE THREAD

**Issue by AnuarHarb** [barranquillajs/Meetups#27]
> Nuestros eventos se rigen por el siguiente [Código de conducta](https://github.com/barranquillajs/codigo-de-conducta) - [https://github.com/barranquillajs/codigo-de-conducta](https://github.com/barranquillajs/codigo-de-conducta)

> Antes de suscribir una charla, recuerda revísarlo para ver si estamos en la misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [x] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Anuar Harb

## ¿Cuál es el título de tu charla?
Mapas 3D en JS y modelos de Gemini en Google Places

## Danos una descripción de tu charla (20 palabras)
Aprende a entregar mapas 3D a la velocidad que los usuarios esperan de la tecnología de renderización de Google. Además, aprenderás a usar las capacidades del modelo de Gemini en la API de Places para mostrar resúmenes útiles de IA generativa de lugares y áreas geográficas en tus apps.

## Danos una breve bio acerca de tí (20 palabras o menos)
Director de la Fundación Código Abierto y CEO de Code Centre. Anuar inició en el mundo de la tecnología en México como desarrollador de Software hace 10 años y ahora en Barranquilla busca fortalecer el ecosistema tech a através de educación especializada, construir comunidad y propiciar salidas laborales. 

## ¿Tienes alguna red social donde podamos contactarte?
https://www.linkedin.com/in/anuarharb/

## ¿Representas a alguna compañía o empresa?
Fundación Código Abierto y Code Centre

## ¿Qué tipo de conector tiene tu notebook?

- [x] HDMI
- [ ] Mini DisplayPort
- [ ] VGA

## ¿Quieres agregar algo más?

-----------
> Muchas Gracias!
> El equipo de @barranquillajs/meetup

**Comment by lporras** [comment]
@AnuarHarb  Vamos a agendar esta charla para el meetup de septiembre 26 del 2024
