### ISSUE TITLE
Luis Reyes tema para el MeetUps

### ISSUE THREAD

**Issue by evolutecc** [barranquillajs/Meetups#29]
> Nuestros eventos se rigen por el siguiente [Código de conducta](https://github.com/barranquillajs/codigo-de-conducta) - [https://github.com/barranquillajs/codigo-de-conducta](https://github.com/barranquillajs/codigo-de-conducta)

> Antes de suscribir una charla, recuerda revísarlo para ver si estamos en la misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [X ] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Luis Carlos Reyes Vanegas

## ¿Cuál es el título de tu charla?
IA Chatbot con Gemini, Next.js y Firebase

## Danos una descripción de tu charla (20 palabras)
Aprende a construir chatbots conversacionales con IA usando Gemini, Next.js y Firebase. Implementa respuestas inteligentes y mejora la interacción en tu sitio web.

## Danos una breve bio acerca de tí (20 palabras o menos)
Soy Luis Reyes dirijo el area de TI de EvolutecC, una fabrica de desarrollo dedicada a productos web, actualmente soy responsable por la operación de +150 proyectos en linea entre sitios web, ecommerce, aplicaciones moviles, startups, software web a la medida, integraciones y otros. Soy apasionado por el mundo de la tecnología y me gusta compartir mis conocimientos, en mis tiempos libres Juego XBOX y entre mis juegos favoritos esta FIFA, FarCry, Resident Evil 4 y A plage tale to reliquem. 

## ¿Tienes alguna red social donde podamos contactarte?
https://www.linkedin.com/in/luis-carlos-reyes-vanegas-803306170/

## ¿Representas a alguna compañía o empresa?
EvolutecC SAS, como Director TI

## ¿Qué tipo de conector tiene tu notebook?

- [X] HDMI
- [ ] Mini DisplayPort
- [ ] VGA

## ¿Quieres agregar algo más?
Cualquier información que aporte valor al tema que necesiten que agrege sería genial!

-----------
> Muchas Gracias!
> El equipo de @barranquillajs/meetup

**Comment by lporras** [comment]
Seleccionada para el meetup de Julio 2024
