### ISSUE TITLE
Postulación de charla - Jesus Hernandez

### ISSUE THREAD

**Issue by JesuHrz** [barranquillajs/Meetups#3]
> Nuestros eventos se rigen por el siguiente [Código de conducta](https://github.com/barranquillajs/codigo-de-conducta) - [https://github.com/barranquillajs/codigo-de-conducta](https://github.com/barranquillajs/codigo-de-conducta)

> Antes de suscribir una charla, recuerda revísarlo para ver si estamos en la misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [x] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Jesus Hernandez

## ¿Cuál es el título de tu charla?
Contribuir al Open Source puede ser mas facil de lo que tu crees

## Danos una descripción de tu charla (20 palabras)
En esta charla hablaremos de como podemos retribuirle al open source la ayuda que nos ha dado y que hacerlo puede ser mas facil de lo que pensamos.

## ¿Tienes alguna red social donde podamos contactarte?

Instagram - Twitter - Github: Jesuhrz

## ¿Qué tipo de conector tiene tu notebook?

- [x] HDMI
- [ ] Mini DisplayPort
- [ ] VGA

-----------
> Muchas Gracias!
> El equipo de @barranquillajs/meetup

**Comment by lporras** [comment]
@JesuHrz muchas gracias por tu propuesta, ¿Te parece bien dar la charla el 17 de septiembre?

**Comment by JesuHrz** [comment]
Si vale, no hay wey @lporras

**Comment by JesuHrz** [comment]
> @JesuHrz muchas gracias por tu propuesta, ¿Te parece bien dar la charla el 17 de septiembre?

Si vale, no hay wey @lporras

**Comment by JesuHrz** [comment]
Soy Jesús Hernández, tengo 26 años y  desarrollador frontend por el alrededor de 7 años y amante al ecosistema de JavaScript ❤️.

Actualmente trabajo para una agencia de desarrollo de software llamada Koombea.

c.c: @lporras
