### ISSUE TITLE
Tema de charla 30 de Mayo

### ISSUE THREAD

**Issue by nicolas-camacho** [barranquillajs/Meetups#30]
> Nuestros eventos se rigen por el siguiente [Código de conducta](https://github.com/barranquillajs/codigo-de-conducta) - [https://github.com/barranquillajs/codigo-de-conducta](https://github.com/barranquillajs/codigo-de-conducta)

> Antes de suscribir una charla, recuerda revísarlo para ver si estamos en la misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [x] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Nicolas Camacho

## ¿Cuál es el título de tu charla?
Building Code for Coders

## Danos una descripción de tu charla (20 palabras)
El foco de la charla esta dirigido a la construcción de productos y/o herramientas para otros desarrolladores, como lo podria ser por ejemplo una librería, la idea es orientar a la toma de decisiones y/o practicas recomendables a la hora de hacerlo.

## Danos una breve bio acerca de tí (20 palabras o menos)
Mi nombre es Nicolas Camacho trabajo como ingeniero de software en Twilio, tengo aproximadamente 5 años trabajando en la industria y soy un apasionado por el codigo y la buena ingeniería.

## ¿Tienes alguna red social donde podamos contactarte?
[Github](https://github.com/nicolas-camacho)
[Linkedin](https://www.linkedin.com/in/nicolas-camacho-aguilar/)

## ¿Representas a alguna compañía o empresa?
No

## ¿Qué tipo de conector tiene tu notebook?

- [x] HDMI
- [ ] Mini DisplayPort
- [ ] VGA

## ¿Quieres agregar algo más?

-----------
> Muchas Gracias!
> El equipo de @barranquillajs/meetup

**Comment by lporras** [comment]
Hola @nicolas-camacho, vamos a agendar tu charla para el meetup del 30 de mayo
