### ISSUE TITLE
Del Desarrollo a la Monetización

### ISSUE THREAD

**Issue by Felipeagq** [barranquillajs/Meetups#32]
> Nuestros eventos se rigen por el siguiente [Código de conducta](https://github.com/barranquillajs/codigo-de-conducta) - [https://github.com/barranquillajs/codigo-de-conducta](https://github.com/barranquillajs/codigo-de-conducta)

> Antes de suscribir una charla, recuerda revísarlo para ver si estamos en la misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [ x ] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Felipe Andres Gonzalez Quintero

## ¿Cuál es el título de tu charla?
Esta charla está diseñada para ayudar a desarrolladores a vender sus servicios de manera efectiva y gestionar de forma integral sus proyectos de desarrollo. Exploraremos cómo posicionarse profesionalmente, manejar la relación con los clientes, y organizar todos los aspectos del desarrollo, desde la recolección de requerimientos hasta la facturación. Además, discutiremos la creación de empresas y la importancia de construir una marca personal sólida

## Danos una descripción de tu charla (20 palabras)
Aprenderemos como siendo desarrolladores podemos monetizar mediante la gestión y organización de proyectos.

## Danos una breve bio acerca de tí (20 palabras o menos)
Soy Felipe Andres Gonzalez Quintero, tengo 25 años, Ingeniero nube de AWS, backend en python y CoFounder de una empresa de desarrollo llamada FEANWARE

## ¿Tienes alguna red social donde podamos contactarte?
https://www.instagram.com/felipeagq_/
https://www.instagram.com/feanware/

## ¿Representas a alguna compañía o empresa?
FEANWARE

## ¿Qué tipo de conector tiene tu notebook?

- [ x ] HDMI
- [ ] Mini DisplayPort
- [ ] VGA

## ¿Quieres agregar algo más?

-----------
> Muchas Gracias!
> El equipo de @barranquillajs/meetup

**Comment by lporras** [comment]
Hola @Felipeagq queda confirmada tu charla para el meetup de Julio.
