### ISSUE TITLE
Prevención de Malas Practicas en Entorno laboral

### ISSUE THREAD

**Issue by tavosalas270** [barranquillajs/Meetups#35]
> Nuestros eventos se rigen por el siguiente [Código de conducta](https://github.com/barranquillajs/codigo-de-conducta) - [https://github.com/barranquillajs/codigo-de-conducta](https://github.com/barranquillajs/codigo-de-conducta)

> Antes de suscribir una charla, recuerda revísarlo para ver si estamos en la misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [X] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Gustavo Adolfo Salas Durán

## ¿Cuál es el título de tu charla?
Prevención de Malas Practicas en Entorno laboral

## Danos una descripción de tu charla (20 palabras)
Hablar de situaciones que se presentan diario en empresas o en areas de TI y el como tratarlas como empleador y empleado.

## Danos una breve bio acerca de tí (20 palabras o menos)
Mi nombre es Gustavo Salas, soy Ingeniero de Sistemas con experiencia en el desarrollo FullStack con un gran interes en la ciencias de datos y un gusto por el anime y vídeojuegos.

## ¿Tienes alguna red social donde podamos contactarte?
GitHub: https://github.com/tavosalas270
LinkedIn: https://www.linkedin.com/in/ing-gustavo-adolfo-salas-duran

## ¿Representas a alguna compañía o empresa?
No
## ¿Qué tipo de conector tiene tu notebook?

- [X] HDMI
- [ ] Mini DisplayPort
- [ ] VGA

## ¿Quieres agregar algo más?
Aspiro poder hacer lo mejor que pueda y queden satisfechos con mi charla.

-----------
> Muchas Gracias!
> El equipo de @barranquillajs/meetup

**Comment by lporras** [comment]
@tavosalas270 Vamos a agendar esta charla para el meetup de septiembre 26 del 2024

**Comment by tavosalas270** [comment]
> @tavosalas270 Vamos a agendar esta charla para el meetup de septiembre 26 del 2024

Muchísimas gracias, quedo atento
