### ISSUE TITLE
Postulación De Charla - Victor Barrios Alvarez

### ISSUE THREAD

**Issue by vbalvarez15** [barranquillajs/Meetups#4]
> Nuestros eventos se rigen por el siguiente [Código de conducta](https://github.com/barranquillajs/codigo-de-conducta) - [https://github.com/barranquillajs/codigo-de-conducta](https://github.com/barranquillajs/codigo-de-conducta)

> Antes de suscribir una charla, recuerda revísarlo para ver si estamos en la misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [x] Keynote (20 a 30 minutos) 
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Víctor Barrios Álvarez

## ¿Cuál es el título de tu charla?
Mercado de aplicaciones hibridas con Ionic, React y Flutter

## Danos una descripción de tu charla (20 palabras)
Los frameworks JavaScript agilizan el trabajo de los programadores a la hora de desarrollar apps. Su utilización garantiza una mayor productividad durante la jornada laboral, agilizando las horas de trabajo volcadas en el desarrollo.

## Danos una breve bio acerca de tí (20 palabras o menos)
Hola, soy Víctor. Actualmente trabajo como arquitecto de software en Técnomóvil SAS. me apasiona el desarrollo web del lado del servidor. Mis Hobbies, son practicar senderismo y una tarde de cine en casa.

## ¿Tienes alguna red social donde podamos contactarte?
Instagram / GitHub: vbalvarez15
Twitter: vbarrios1512

## ¿Representas a alguna compañía o empresa?
NO

## ¿Qué tipo de conector tiene tu notebook?

- [x] HDMI
- [ ] Mini DisplayPort
- [ ] VGA

## ¿Quieres agregar algo más?

-----------
> Muchas Gracias!
> El equipo de @barranquillajs/meetup

**Comment by lporras** [comment]
@vbalvarez15 podrias dar la charla en el meetup de 13 de septiembre?
