### ISSUE TITLE
Como crear codigo irrompible

### ISSUE THREAD

**Issue by makinox** [barranquillajs/Meetups#8]
> Nuestros eventos se rigen por el siguiente [Código de conducta](https://github.com/barranquillajs/codigo-de-conducta) - [https://github.com/barranquillajs/codigo-de-conducta](https://github.com/barranquillajs/codigo-de-conducta)

> Antes de suscribir una charla, recuerda revísarlo para ver si estamos en la misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [x] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Jesus Bossa

## ¿Cuál es el título de tu charla?
Como crear codigo irrompible

## Danos una descripción de tu charla (20 palabras)
En resumidas cuentas exponer como funciona el codigo y porque se rompe o se llega a un estado bloqueante de error tant comun en aplicaciones web y sobre la charla explicar como evitar o mejorar esa practica

## Danos una breve bio acerca de tí (20 palabras o menos)
Soy jesus bossa, mas de 6 años creando experiencias digitales, ultimamente trabajo en eva center creando productos para salvar vidas.

## ¿Tienes alguna red social donde podamos contactarte?
- https://jesusbossa.dev
- https://github.com/makinox
- https://www.instagram.com/makinoxz
- https://www.linkedin.com/in/makinox
- https://twitter.com/jesMakinox

## ¿Representas a alguna compañía o empresa?
no

## ¿Qué tipo de conector tiene tu notebook?

- [x] HDMI
- [ ] Mini DisplayPort
- [ ] VGA

## ¿Quieres agregar algo más?
Les compartire las slides por aca

-----------
> Muchas Gracias!
> El equipo de @barranquillajs/meetup

**Comment by lporras** [comment]
Esta charla fue presentada en el meetup de [Noviembre 2022](https://www.meetup.com/barranquillajs/events/289361893/)
